feat(map-control): rotate compass
visgl/loaders.gl-showcases pull request #133
Opened 2022-07-19 22:17 UTC by kirillovzah

2022-07-20 12:59 UTC, belom88 requested changes

2022-07-20 12:59 UTC, belom88 commented on src/pages/comparison/comparison.tsx
> +        bearing: bearing + -bearing,
```suggestion
        bearing: 0,
```

2022-07-20 13:08 UTC, dryabinin-actionengine requested changes

2022-07-25 12:53 UTC, belom88 approved these changes

2022-08-03 10:26 UTC, dryabinin-actionengine approved these changes

2022-08-03 10:26 UTC, merged