test: add e2e tests for viewer
visgl/loaders.gl-showcases pull request #15
Opened 2022-02-21 09:18 UTC by kirillovzah

2022-02-21 10:11 UTC, dryabinin-actionengine requested changes

2022-02-21 10:11 UTC, dryabinin-actionengine commented on src/pages/viewer-app/e2e.viewer-app.spec.ts
> +      expect(await page.select('#tileset', item)).toEqual([item]);
Will be good to detect that tileset really has been changed not only in selector.
WE can't detect it in canvas but, memory stats widget displays tcurrent ileset url.
You can check it.

2022-02-21 10:11 UTC, dryabinin-actionengine commented on src/pages/viewer-app/e2e.viewer-app.spec.ts
> +  it('Contains building explorer', async () => {
Please add tests for internal check boxes

2022-02-21 10:11 UTC, dryabinin-actionengine commented on src/pages/viewer-app/e2e.viewer-app.spec.ts
> +    await page.click('#change-terrain');
Check if toogle is changing state from 'active' to 'not active' and vice versa.

2022-02-21 10:12 UTC, dryabinin-actionengine commented
Good Job!
Please fix conflicts and fix my comments.

2022-02-22 13:08 UTC, belom88 requested changes

2022-02-22 13:08 UTC, belom88 commented on src/pages/viewer-app/e2e.viewer-app.spec.ts
> +    await page.click("#change-terrain");
I don't like creating new props for testing. You can use more long selector here `#terrain-layer-switch>span`

2022-02-22 13:08 UTC, belom88 commented on src/components/toogle-switch/toggle-switch.tsx
> +  sliderId = '',
I don't like this new prop. It is added only for testing that is not good. You can use more difficult selector instead:
`#[parentTogleSwitchId]>span`

2022-02-22 13:08 UTC, belom88 commented on src/pages/dashboard/e2e.dashboard.spec.ts
> +});
Add new line in the end of the file

2022-02-24 10:55 UTC, dryabinin-actionengine requested changes

2022-02-24 10:55 UTC, dryabinin-actionengine commented on src/components/toogle-switch/toggle-switch.tsx
> +          onChange={onChange}
Remove extra space.

2022-02-28 10:47 UTC, belom88 requested changes

2022-02-28 10:47 UTC, belom88 commented on jest-puppeteer.config.js
> +};
Why this file is in the changes?

2022-02-28 15:31 UTC, dryabinin-actionengine commented
Will close this PR because this branch was crated from fork repo and now PR is open from original repo here - https://github.com/visgl/loaders.gl-showcases/pull/30

2022-02-28 15:31 UTC, closed without merging