feat(attributes-panel): add colorize by attribute section
visgl/loaders.gl-showcases pull request #172
Opened 2022-09-15 10:53 UTC by kirillovzah

2022-09-15 19:18 UTC, belom88 requested changes

2022-09-15 19:18 UTC, belom88 commented on src/components/attributes-panel/attributes-stats/color-value-item.tsx
> +  yearCount?: number;
year?

2022-09-15 19:18 UTC, belom88 commented on src/components/attributes-panel/attributes-stats/attribute-stats.tsx
> +                      yearCount={Math.floor(statistics.avg)}
I won't be able to visualize it with distribution avg calculated. Let's calculate it from min and max values

2022-09-15 19:18 UTC, belom88 commented on src/components/attributes-panel/attributes-stats/attribute-stats.tsx
> +          {statistics?.max && statistics?.avg && (
```suggestion
          {statistics?.max && statistics?.min && (
```

2022-09-15 19:18 UTC, belom88 commented on src/components/attributes-panel/attributes-stats/attribute-stats.tsx
> +const NOT_VISIBLE = false;
Don't use these constants. They are excess

2022-09-15 19:18 UTC, belom88 commented on src/components/attributes-panel/attributes-panel.tsx
> +  const [showColorizeByAttribute, setShowColorizeByAttribute] =
Move this state to `AttributeStats` level

2022-09-30 16:42 UTC, belom88 requested changes

2022-09-30 16:42 UTC, belom88 commented on src/components/attributes-panel/attributes-panel.tsx
> +
too many extra lines

2022-09-30 16:42 UTC, belom88 commented on src/components/attributes-panel/attributes-stats/attribute-stats.spec.tsx
> +
too many extra lines

2022-09-30 16:42 UTC, belom88 commented on src/components/attributes-panel/attributes-stats/attribute-stats.spec.tsx
> +    const histogramIcon = screen.getByText("Histogram").firstElementChild
```suggestion
    const histogramIcon = screen.getByText("Histogram").firstElementChild;
```

2022-09-30 16:42 UTC, belom88 commented on src/components/attributes-panel/attributes-stats/attribute-stats.spec.tsx
> +    const histogramIcon = screen.getByText("Histogram").firstElementChild
Declare the variable in the place it is used

2022-09-30 16:42 UTC, belom88 commented on src/components/attributes-panel/attributes-stats/attribute-stats.tsx
> +                    data-testid={"histogram-arrow"}
Can we remove `data-testid` yet?

2022-09-30 16:42 UTC, belom88 commented on src/utils/calculate-average-value.ts
> +  };
New line in the end needed

2022-09-30 16:42 UTC, belom88 commented on src/utils/hooks/use-expand.ts
> +import { useCallback, useState } from "react";
Add tests

2022-09-30 16:42 UTC, belom88 commented on src/utils/calculate-average-value.spec.ts
> +describe("Format Memory", () => {
```suggestion
describe("Calculate average value", () => {
```

2022-10-01 07:30 UTC, belom88 requested changes
Just "0" in the place
![image](https://user-images.githubusercontent.com/18549629/193398322-00eae9cc-b3d0-4015-a382-efe94cfd5ffd.png)

2022-10-03 11:14 UTC, ibgreen commented
Nit: Way too many decimals. Suggest truncating to 3 or possibly 4 significant digits.

2022-10-03 12:27 UTC, belom88 approved these changes

2022-10-03 12:27 UTC, belom88 commented on src/utils/calculate-average-value.ts
> +
Something wrong here. Probably - 9nth line is not empty

2022-10-03 13:16 UTC, merged