chore(layers-panel): added insert-scene-panel
visgl/loaders.gl-showcases pull request #179
Opened 2022-10-06 08:33 UTC by dryabinin-actionengine

2022-10-12 15:26 UTC, belom88 requested changes

2022-10-12 15:26 UTC, belom88 commented on src/components/comparison/layers-panel/layers-panel.tsx
> +                title={EXISTING_AREA_WARNING}
The conten of the warning is the same as for `showExistedLayerWarning`. We could use `showExistedLayerWarning` and its warning for the insert scene.

2022-10-12 15:26 UTC, belom88 commented on src/components/comparison/layers-panel/layers-panel.tsx
> +      setShowNoSupportedLayersInSceneWarning(true);
That was about another logic. If the scene has at least one unsupported layer, the warning should be shown.
If the webscene doesn't contain the data type of children, we need to load layer.json of each child to check.

2022-10-12 15:26 UTC, belom88 commented on src/components/comparison/layers-panel/layers-panel.tsx
> +
Strange comment

2022-10-17 13:15 UTC, belom88 approved these changes

2022-10-31 13:57 UTC, dryabinin-actionengine commented
Closed because of https://github.com/visgl/loaders.gl-showcases/pull/194

2022-10-31 13:57 UTC, closed without merging