feat(website): initial project setup
visgl/loaders.gl-showcases pull request #2
Opened 2022-02-02 13:00 UTC by dryabinin-actionengine

2022-02-02 14:31 UTC, dariaterekhovaae commented on src/pages/i3s-app/app.tsx
> +    const metadata = await fetch(metadataUrl).then((resp) => resp.json());
Please move all async logic to useEffect with appropriate dependencies

2022-02-02 14:55 UTC, belom88 requested changes

2022-02-02 15:51 UTC, ibgreen approved these changes

2022-02-08 13:47 UTC, belom88 approved these changes

2022-02-08 14:23 UTC, merged