feat(home-page): adaptive design
visgl/loaders.gl-showcases pull request #206
Opened 2022-11-16 12:55 UTC by kirillovzah

2022-11-17 09:26 UTC, belom88 requested changes
* `public/images/app-showcase.png` (6.11MB) and `public/images/tools-background.png` (2.84MB) are too big. We need to reduce size.
* I prefere scroll to work on mobile for the whole content
* add e2e tests to check content and links

2022-11-28 18:15 UTC, belom88 commented
'public/images/app-showcase.png' - 1.37 MB is still huge. This file is used on mobile. It should be much smaller.
![image](https://user-images.githubusercontent.com/18549629/204350523-150f4545-9e4f-4f4e-9ba2-2205e99ae5c4.png)
`intrinsic size` should be equal to `rendered size`.
Please check size of all *.png of this PR not only 'public/images/app-showcase.png'

2022-11-29 10:48 UTC, dryabinin-actionengine commented
> 'public/images/app-showcase.png' - 1.37 MB is still huge. This file is used on mobile. It should be much smaller. ![image](https://user-images.githubusercontent.com/18549629/204350523-150f4545-9e4f-4f4e-9ba2-2205e99ae5c4.png) `intrinsic size` should be equal to `rendered size`. Please check size of all *.png of this PR not only 'public/images/app-showcase.png'

I also suggest to convert all png, jpg -> webp format it will increase performance of loading images.
https://developers.google.com/speed/webp#:~:text=WebP%20is%20a%20modern%20image,in%20size%20compared%20to%20PNGs.

2022-12-14 17:14 UTC, belom88 approved these changes

2022-12-19 13:08 UTC, merged