chore(tile-info): validate tile panel
visgl/loaders.gl-showcases pull request #233
Opened 2022-12-29 11:59 UTC by kirillovzah

2023-01-09 10:05 UTC, dryabinin-actionengine commented
When scroll bar is presented there is a visual issue with icon collapsing.
![image](https://user-images.githubusercontent.com/70207219/211283694-2b83bb74-1f80-43ba-bb43-5f7dd0732f39.png)

2023-01-09 10:10 UTC, dryabinin-actionengine commented
Also mobile version is not on the right place.
How it should be:
![image](https://user-images.githubusercontent.com/70207219/211284181-ac106042-2956-45e0-92f5-764332620a1b.png)
How it is now:
![image](https://user-images.githubusercontent.com/70207219/211284242-801b5be5-5b47-4f02-ba26-d8d51fb69d01.png)

2023-01-09 10:52 UTC, dryabinin-actionengine requested changes

2023-01-09 10:52 UTC, dryabinin-actionengine commented on src/app.tsx
> +  validate_tile_warning_dark,
Please rename it in more common way. Try to abstract from particular coloring component names.
Follow the exiting naming convention.

2023-01-13 08:16 UTC, belom88 approved these changes

2023-01-13 11:35 UTC, dryabinin-actionengine approved these changes

2023-01-13 11:36 UTC, merged