chore(tile-info): update design of normals section
visgl/loaders.gl-showcases pull request #239
Opened 2023-01-17 13:28 UTC by kirillovzah

2023-01-18 10:49 UTC, dryabinin-actionengine approved these changes

2023-01-18 10:49 UTC, dryabinin-actionengine commented on src/components/common.tsx
> +`;
Please add empty line

2023-01-19 07:53 UTC, belom88 requested changes

2023-01-19 07:53 UTC, belom88 commented on src/components/tile-details-panel/normals-input.tsx
> +import styled from "styled-components";
file name should be equal component's name: `normals-input-item.tsx`

2023-01-19 07:53 UTC, belom88 commented on src/components/tile-details-panel/normals-input.tsx
> +import styled from "styled-components";
or rename the component

2023-01-19 07:53 UTC, belom88 commented on src/components/tile-details-panel/normals.tsx
> +  handleChangeNormalsLength: (tile: Tile3D, length: number) => void;
Callback name should be `onMakeSomething`. Handler might be `hanleMakeSomething` of `onMakeSomethingHandler`

2023-01-24 08:52 UTC, belom88 approved these changes

2023-01-24 09:55 UTC, merged