fix(attribute-stats): capital letter in statistic
visgl/loaders.gl-showcases pull request #241
Opened 2023-01-18 10:10 UTC by kirillovzah

2023-01-18 13:38 UTC, dryabinin-actionengine requested changes
Tests are failed

2023-01-18 13:38 UTC, dryabinin-actionengine commented on src/components/attributes-panel/attributes-stats/attribute-stats.tsx
> +
Move this function to utils + write tests.

2023-01-19 11:11 UTC, belom88 requested changes

2023-01-19 11:11 UTC, belom88 commented on src/utils/capitalize.ts
> +export const capitalize = (str: string) =>
I feel we can add this function to `format-utils.ts`

2023-01-22 17:51 UTC, belom88 approved these changes

2023-01-24 09:35 UTC, dryabinin-actionengine approved these changes

2023-01-24 09:37 UTC, merged