added new map components, fixed compilation errors, added vite
visgl/loaders.gl-showcases pull request #304
Opened 2023-10-23 11:10 UTC by unclFedor

2023-10-23 13:04 UTC, belom88 requested changes
A lot of excess code we should get rid of in this PR.

2023-10-23 16:09 UTC, unclFedor commented on .env.local
> +VITE_REACT_APP_REST_API_APP_ID=97B28D2ED40DA08AB53687356
removed .env.local

2023-10-23 16:13 UTC, unclFedor commented on .env
> +VITE_SOME_KEY=hello
1. removed VITE_ prefix in the .env content
2. uninstalled "vite" 
3. installed "dotenv". It seems "@types/dotenv" is deprecated
4. updated webpack.dev.config.js

2023-10-23 16:43 UTC, unclFedor commented on package.json
> +    "@mui/material": "^5.14.13",
1. removed @mui/material  from package.json
2. removed loading.tsx, unsupported.tsx
3. updated map-wrapper.tsx

2023-10-24 08:06 UTC, unclFedor commented on package.json
>      "deck.gl": "^8.8.3",
1. removed "deck.gl": "^8.8.3"
2. added 
"@deck.gl/geo-layers": "^8.9.31",
"@deck.gl/layers": "^8.9.31",
"@deck.gl/mesh-layers": "^8.9.31",
"@deck.gl/react": "^8.9.31", 
"@loaders.gl/images": "^4.0.0-beta.2",
"@loaders.gl/schema": "^4.0.0-beta.2",
"apache-arrow": "^13.0.0",

2023-10-24 09:37 UTC, unclFedor commented on src/components/interleaved-map/interleaved-map.tsx
> +import { Map as MapboxMap } from "mapbox-gl";
removed interleaved-map.tsx

2023-10-24 09:39 UTC, unclFedor commented on src/components/loading/loading.tsx
> +import CircularProgress from "@mui/material/CircularProgress";
1. Removed "@mui/material 
2. Removed loading .tsx

2023-10-24 09:39 UTC, unclFedor commented on src/components/unsupported/unsupported.tsx
> +import Paper from "@mui/material/Paper";
removed unsupported.tsx

2023-10-24 12:06 UTC, unclFedor commented on src/constants/notification-messages.ts
> +export const TERRAIN_WITH_SELECTED_BASE_MAP_PROVIDER_IS_NOT_SUPPORTED = (
removed notification-messages.ts

2023-10-24 21:43 UTC, unclFedor commented on src/components/deck-gl-wrapper/deck-gl-wrapper.tsx
> +            maxzoom={14}
replaced to {mapProviderProps[BaseMapProviderId.mapbox2].terrainProps.XXX} and {mapProviderProps[BaseMapProviderId.maplibre].terrainProps.XXX} accordingly.

2023-10-25 17:25 UTC, unclFedor commented on src/components/deck-gl-wrapper/deck-gl-wrapper.tsx
> +      : BaseMapProviderId.mapbox2;
removed expression. Changed type from String to BaseMapProviderId

2023-12-04 11:24 UTC, closed without merging