feat(tile-inspector): show original texture
visgl/loaders.gl-showcases pull request #349
Opened 2024-02-06 09:37 UTC by mspivak-actionengine

2024-02-13 10:13 UTC, belom88 requested changes

2024-02-13 10:13 UTC, belom88 commented on src/components/tile-details-panel/texture-section.tsx
> +const isFormatSupported = (gl, format) => {
Move functions to utils. I think `src\utils\debug\texture-render-utils.ts` is a right place

2024-02-13 10:13 UTC, belom88 commented on src/components/tile-details-panel/texture-section.tsx
> +const createCompressedTexture2D = (gl, images) => {
Add TSDoc and types

2024-02-13 10:13 UTC, belom88 commented on src/components/tile-details-panel/texture-section.tsx
> +
```suggestion
```

2024-02-13 10:13 UTC, belom88 commented on src/components/tile-details-panel/texture-section.tsx
> +        drawCompressedTexture(image, AREA_SIZE).then((ret) => {
```suggestion
        drawCompressedTexture(image, AREA_SIZE).then((result) => {
```

2024-02-13 10:13 UTC, belom88 commented on src/components/tile-details-panel/texture-section.tsx
> +type SIZE = {
Caps is for constants

```suggestion
type Size = {
```

2024-02-13 10:13 UTC, belom88 commented on src/components/tile-details-panel/texture-section.tsx
> +    width: AREA_SIZE,
Confusing naming. "Area" is something equal to `width`*`height`

```suggestion
    width: SIZE,
```

2024-02-13 21:03 UTC, mspivak-actionengine commented on src/components/modal-dialog/modal-dialog.tsx
> +const AfterButtonsContainer = styled.div`
Done.

2024-02-13 21:03 UTC, mspivak-actionengine commented on src/components/tile-details-panel/texture-section.tsx
> +const createCompressedTexture2D = (gl, images) => {
Done.

2024-02-13 21:04 UTC, mspivak-actionengine commented on src/components/tile-details-panel/texture-section.tsx
> +
Done.

2024-02-13 21:04 UTC, mspivak-actionengine commented on src/components/tile-details-panel/texture-section.tsx
> +        drawCompressedTexture(image, AREA_SIZE).then((ret) => {
Done.

2024-02-13 21:04 UTC, mspivak-actionengine commented on src/components/tile-details-panel/texture-section.tsx
> +type SIZE = {
Done.

2024-02-19 10:46 UTC, belom88 approved these changes

2024-02-19 10:46 UTC, belom88 commented on src/utils/debug/texture-render-utils.ts
> +  data: any,
Add types for `data`

2024-02-20 09:05 UTC, mspivak-actionengine commented on src/utils/debug/texture-render-utils.ts
> +  data: any,
Done

2024-02-20 09:12 UTC, merged