feat: slpk from local filesystem feature
visgl/loaders.gl-showcases pull request #377
Opened 2024-11-18 21:51 UTC by dariaterekhova-actionengine

First part of changes for slpk from local filesystem feature

2024-11-27 11:53 UTC, dsavinov-actionengine commented
@belom88 Please review as soon as you can

2024-11-27 16:42 UTC, belom88 requested changes

2024-11-27 16:42 UTC, belom88 commented on src/redux/slices/flattened-sublayers-slice.ts
> +      console.log("error", e);
```suggestion
      console.error(e);
```

2024-11-27 16:42 UTC, belom88 commented on src/redux/slices/flattened-sublayers-slice.ts
> +  if (typeof tilesetData.url !== "string") {
Add a test case

2024-11-27 16:42 UTC, belom88 commented on src/pages/viewer-app/viewer-app.tsx
> +      const tilesetDataUrl = typeof tilesetsData[0].url === "string" ? tilesetsData[0].url : tilesetsData[0].url.name;
Some utility `function getDatasetUrl(dataset: LayerExample | TilesetMetadata) => string`. You reuse this pattern many times. This function would make the code more readable.

```suggestion
      const tilesetDataUrl = getDatasetUrl(tilesetsData[0]);
```

2024-11-27 16:42 UTC, belom88 commented on src/pages/viewer-app/viewer-app.tsx
> +      }
Why this part is different in `src/pages/debug-app/debug-app.tsx`  and `src/components/comparison/comparison-side/comparison-side.tsx`?

2024-11-28 09:16 UTC, belom88 approved these changes

2024-11-28 09:16 UTC, belom88 commented on src/utils/layer-utils.ts
> +    if (tileset.url.includes(typeof example.url === "string" ? example.url : example.url.name) && !example.viewState) {
```suggestion
    if (tileset.url.includes(getLayerUrl(example.url)) && !example.viewState) {
```

2024-11-28 13:43 UTC, merged