feat(header): add compare tab for default view
visgl/loaders.gl-showcases pull request #75
Opened 2022-05-17 14:49 UTC by dryabinin-actionengine

![image](https://user-images.githubusercontent.com/70207219/168841387-d06adcb8-994d-43e0-9f58-4e386ae7afe9.png)
![image](https://user-images.githubusercontent.com/70207219/168841440-28a16dc5-6139-46f9-8558-0f2bf9d0ef59.png)

2022-05-18 08:04 UTC, belom88 requested changes

2022-05-18 12:34 UTC, dryabinin-actionengine commented on src/components/header/header.tsx
> +        {/* TODO Add outside click detection to close  Compare Tab*/}
Ok, done

2022-05-18 12:58 UTC, dryabinin-actionengine commented on src/pages/dashboard/e2e.dashboard.spec.ts
> +    expect(currentUrl).toBe("http://localhost:3000/comparison/across-layers");
Done

2022-05-23 08:47 UTC, belom88 approved these changes

2022-05-23 09:20 UTC, merged